package Tema2_EstructuraLineal;


public class ArrayStackTest1 {
    public static void main(String[] args) {
     // PRINCIPAL
   
    Stack<Integer> a= new ArrayStack<>();
    Stack<Integer> b= new ArrayStack<>();
    Stack<Integer> c= new ArrayStack<>();
    Stack<Integer> d= new ArrayStack<>();
  
//    
//        System.out.println("caso 1 del ejercicio 6.2");
//        System.out.println(a.top());
//        System.out.println(a.top());
//        System.out.println(a.top());
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.push(Integer.SIZE);
        a.top();
        a.top();
        a.top();
        a.top();
        a.top();
        a.top();
        a.top();
        a.top();
        a.top();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        a.pop();
        System.out.println(a.size());
        
        System.out.println("");
        
        System.out.println("Caso 2 del ejercicio 6.2");
        System.out.println(b.top());
        System.out.println(b.top());
        System.out.println(b.pop());
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.push(Integer.SIZE);
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.top();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        b.pop();
        System.out.println(b.size());
        
        System.out.println("");
        
        System.out.println("Caso 3 del ejercicio 6.2");
        System.out.println(c.top());
        System.out.println(c.pop());
        System.out.println(c.pop());
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.push(Integer.SIZE);
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.top();
        c.pop();
        c.pop();
        c.pop();
        c.pop();
        c.pop();
        c.pop();
        c.pop();
        c.pop();
        System.out.println(c.size());
        System.out.println("");
        
        System.out.println("Caso 4 del ejercicio 6.2");
        System.out.println(d.pop());
        System.out.println(d.pop());
        System.out.println(d.pop());
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.push(Integer.SIZE);
        d.pop();
        d.pop();
        d.pop();
        d.pop();
        d.pop();
        d.pop();
        d.pop();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        d.top();
        System.out.println(d.size());


    }
  
}
