
package Tema2_EstructuraLineal;

/**
 *
 * @author Brandy
 */
public class ArrayQueueTest {
    public static void main(String[] args) {
//        ArrayQueue<Integer> aq = new ArrayQueue();
        ArrayQueue<Integer> Q = new ArrayQueue();
        ArrayQueue<Integer> R= new ArrayQueue();
        ArrayQueue<Integer>S= new ArrayQueue();
        ArrayQueue<Integer> T = new ArrayQueue();
        ArrayQueue<Integer> U= new ArrayQueue();
        ArrayQueue<Integer> V= new ArrayQueue();
        ArrayQueue<Integer>Z= new ArrayQueue();
        
        Z.enqueue(5);
        Z.enqueue(3);
        System.out.println(Z.dequeue());
        Z.enqueue(2);
        Z.enqueue(8);
        System.out.println(Z.dequeue());
        System.out.println(Z.dequeue());
        Z.enqueue(9);
        Z.enqueue(1);
        System.out.println(Z.dequeue());
        Z.enqueue(7);
        Z.enqueue(6);
        System.out.println(Z.dequeue());
        System.out.println(Z.dequeue());
        Z.enqueue(4);
        System.out.println(Z.dequeue());
        System.out.println(Z.dequeue());
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
//        aq.enqueue(5);
//        aq.enqueue(3);
//        System.out.println(aq.size());
//        System.out.println(aq.dequeue());
//        System.out.println(aq.isEmpty());
//        System.out.println(aq.dequeue());
//        System.out.println(aq.isEmpty());
//        System.out.println(aq.dequeue());
//        aq.enqueue(7);
//        aq.enqueue(9);
//        System.out.println(aq.first());
//        aq.enqueue(4);
        
        System.out.println("Caso 1 del ejercicio 6.7");
        System.out.println(Q.first());
        System.out.println(Q.first());
        System.out.println(Q.first());
        System.out.println(Q.first());
        System.out.println(Q.first());
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);  
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        Q.enqueue(Integer.SIZE);
        
        Q.first();
        Q.first();
        Q.first();
        Q.first();
        Q.first();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        Q.dequeue();
        System.out.println(Q.size());
        
        System.out.println("Caso 2 del ejercicio 6.7");
        System.out.println(R.first());
        System.out.println(R.first());
        System.out.println(R.first());
        System.out.println(R.first());
        System.out.println(R.dequeue());
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
        R.enqueue(Integer.SIZE);
      
        R.first();
        R.first();
        R.first();
        R.first();
        R.first();
        R.first();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        R.dequeue();
        System.out.println(R.size());
        
        System.out.println("Caso 3 del ejercicio 6.7");
        System.out.println(S.first());
        System.out.println(S.first());
        System.out.println(S.first());
        System.out.println(S.dequeue());
        System.out.println(S.dequeue());
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
        S.enqueue(Integer.SIZE);
      
        S.first();
        S.first();
        S.first();
        S.first();
        S.first();
        S.first();
        S.first();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        S.dequeue();
        System.out.println(S.size());
        
        System.out.println("Caso 4 del ejercicio 6.7");
        System.out.println(T.first());
        System.out.println(T.first());
        System.out.println(T.dequeue());
        System.out.println(T.dequeue());
        System.out.println(T.dequeue());
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
        T.enqueue(Integer.SIZE);
      
        T.first();
        T.first();
        T.first();
        T.first();
        T.first();
        T.first();
        T.first();
        T.first();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        T.dequeue();
        System.out.println(T.size());
        
        System.out.println("Caso 5 del ejercicio 6.7");
        System.out.println(U.first());
        System.out.println(U.dequeue());
        System.out.println(U.dequeue());
        System.out.println(U.dequeue());
        System.out.println(U.dequeue());
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
        U.enqueue(Integer.SIZE);
       
        U.first();
        U.first();
        U.first();
        U.first();
        U.first();
        U.first();
        U.first();
        U.first();
        U.first();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        U.dequeue();
        System.out.println(U.size());
        
        System.out.println("Caso 6 del ejercicio 6.7");
        System.out.println(V.dequeue());
        System.out.println(V.dequeue());
        System.out.println(V.dequeue());
        System.out.println(V.dequeue());
        System.out.println(V.dequeue());
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.enqueue(Integer.SIZE);
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.first();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        V.dequeue();
        System.out.println(V.size());
       
    }
}
